# Generated by Django 3.2.9 on 2021-12-01 16:08

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20211201_1008'),
        ('users', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_addresss',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='address.address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailing_addresss',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_address', to='address.address'),
        ),
    ]
