# Generated by Django 3.2.9 on 2021-12-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20211127_0949'),
        ('users', '0006_auto_20211201_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='prefer_payment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='prefer_table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.table'),
        ),
    ]
