# Generated by Django 3.2.9 on 2021-12-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211201_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefer_payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
